// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/michael-freling/claude-code-tools/internal/forge/container (interfaces: ContainerManager)
//
// Generated by this command:
//
//	mockgen -destination=mock_container_manager_test.go -package=forge github.com/michael-freling/claude-code-tools/internal/forge/container ContainerManager
//

// Package forge is a generated GoMock package.
package forge

import (
	context "context"
	reflect "reflect"
	time "time"

	container "github.com/michael-freling/claude-code-tools/internal/forge/container"
	gomock "go.uber.org/mock/gomock"
)

// MockContainerManager is a mock of ContainerManager interface.
type MockContainerManager struct {
	ctrl     *gomock.Controller
	recorder *MockContainerManagerMockRecorder
	isgomock struct{}
}

// MockContainerManagerMockRecorder is the mock recorder for MockContainerManager.
type MockContainerManagerMockRecorder struct {
	mock *MockContainerManager
}

// NewMockContainerManager creates a new mock instance.
func NewMockContainerManager(ctrl *gomock.Controller) *MockContainerManager {
	mock := &MockContainerManager{ctrl: ctrl}
	mock.recorder = &MockContainerManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContainerManager) EXPECT() *MockContainerManagerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockContainerManager) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockContainerManagerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockContainerManager)(nil).Close))
}

// ConnectNetwork mocks base method.
func (m *MockContainerManager) ConnectNetwork(ctx context.Context, networkName, containerName string, aliases []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectNetwork", ctx, networkName, containerName, aliases)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConnectNetwork indicates an expected call of ConnectNetwork.
func (mr *MockContainerManagerMockRecorder) ConnectNetwork(ctx, networkName, containerName, aliases any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectNetwork", reflect.TypeOf((*MockContainerManager)(nil).ConnectNetwork), ctx, networkName, containerName, aliases)
}

// ContainerLogs mocks base method.
func (m *MockContainerManager) ContainerLogs(ctx context.Context, containerID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerLogs", ctx, containerID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerLogs indicates an expected call of ContainerLogs.
func (mr *MockContainerManagerMockRecorder) ContainerLogs(ctx, containerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerLogs", reflect.TypeOf((*MockContainerManager)(nil).ContainerLogs), ctx, containerID)
}

// CreateNetwork mocks base method.
func (m *MockContainerManager) CreateNetwork(ctx context.Context, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNetwork", ctx, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNetwork indicates an expected call of CreateNetwork.
func (mr *MockContainerManagerMockRecorder) CreateNetwork(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNetwork", reflect.TypeOf((*MockContainerManager)(nil).CreateNetwork), ctx, name)
}

// EnsureSharedNetwork mocks base method.
func (m *MockContainerManager) EnsureSharedNetwork(ctx context.Context, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureSharedNetwork", ctx, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureSharedNetwork indicates an expected call of EnsureSharedNetwork.
func (mr *MockContainerManagerMockRecorder) EnsureSharedNetwork(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureSharedNetwork", reflect.TypeOf((*MockContainerManager)(nil).EnsureSharedNetwork), ctx, name)
}

// ImageExists mocks base method.
func (m *MockContainerManager) ImageExists(ctx context.Context, image string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImageExists", ctx, image)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImageExists indicates an expected call of ImageExists.
func (mr *MockContainerManagerMockRecorder) ImageExists(ctx, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImageExists", reflect.TypeOf((*MockContainerManager)(nil).ImageExists), ctx, image)
}

// IsContainerRunning mocks base method.
func (m *MockContainerManager) IsContainerRunning(ctx context.Context, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsContainerRunning", ctx, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsContainerRunning indicates an expected call of IsContainerRunning.
func (mr *MockContainerManagerMockRecorder) IsContainerRunning(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsContainerRunning", reflect.TypeOf((*MockContainerManager)(nil).IsContainerRunning), ctx, name)
}

// ListForgeContainers mocks base method.
func (m *MockContainerManager) ListForgeContainers(ctx context.Context) ([]container.ContainerInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForgeContainers", ctx)
	ret0, _ := ret[0].([]container.ContainerInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForgeContainers indicates an expected call of ListForgeContainers.
func (mr *MockContainerManagerMockRecorder) ListForgeContainers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForgeContainers", reflect.TypeOf((*MockContainerManager)(nil).ListForgeContainers), ctx)
}

// PullImage mocks base method.
func (m *MockContainerManager) PullImage(ctx context.Context, image string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullImage", ctx, image)
	ret0, _ := ret[0].(error)
	return ret0
}

// PullImage indicates an expected call of PullImage.
func (mr *MockContainerManagerMockRecorder) PullImage(ctx, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullImage", reflect.TypeOf((*MockContainerManager)(nil).PullImage), ctx, image)
}

// RemoveContainer mocks base method.
func (m *MockContainerManager) RemoveContainer(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveContainer", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveContainer indicates an expected call of RemoveContainer.
func (mr *MockContainerManagerMockRecorder) RemoveContainer(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveContainer", reflect.TypeOf((*MockContainerManager)(nil).RemoveContainer), ctx, name)
}

// RemoveNetwork mocks base method.
func (m *MockContainerManager) RemoveNetwork(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveNetwork", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveNetwork indicates an expected call of RemoveNetwork.
func (mr *MockContainerManagerMockRecorder) RemoveNetwork(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveNetwork", reflect.TypeOf((*MockContainerManager)(nil).RemoveNetwork), ctx, name)
}

// StartAgent mocks base method.
func (m *MockContainerManager) StartAgent(ctx context.Context, opts container.AgentOptions) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartAgent", ctx, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartAgent indicates an expected call of StartAgent.
func (mr *MockContainerManagerMockRecorder) StartAgent(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartAgent", reflect.TypeOf((*MockContainerManager)(nil).StartAgent), ctx, opts)
}

// StartGateway mocks base method.
func (m *MockContainerManager) StartGateway(ctx context.Context, opts container.GatewayOptions) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartGateway", ctx, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartGateway indicates an expected call of StartGateway.
func (mr *MockContainerManagerMockRecorder) StartGateway(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartGateway", reflect.TypeOf((*MockContainerManager)(nil).StartGateway), ctx, opts)
}

// StartGitHubMCP mocks base method.
func (m *MockContainerManager) StartGitHubMCP(ctx context.Context, opts container.GitHubMCPOptions) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartGitHubMCP", ctx, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartGitHubMCP indicates an expected call of StartGitHubMCP.
func (mr *MockContainerManagerMockRecorder) StartGitHubMCP(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartGitHubMCP", reflect.TypeOf((*MockContainerManager)(nil).StartGitHubMCP), ctx, opts)
}

// StartSharedService mocks base method.
func (m *MockContainerManager) StartSharedService(ctx context.Context, opts container.SharedServiceOptions) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartSharedService", ctx, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartSharedService indicates an expected call of StartSharedService.
func (mr *MockContainerManagerMockRecorder) StartSharedService(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSharedService", reflect.TypeOf((*MockContainerManager)(nil).StartSharedService), ctx, opts)
}

// StopContainer mocks base method.
func (m *MockContainerManager) StopContainer(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopContainer", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopContainer indicates an expected call of StopContainer.
func (mr *MockContainerManagerMockRecorder) StopContainer(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopContainer", reflect.TypeOf((*MockContainerManager)(nil).StopContainer), ctx, name)
}

// WaitForReady mocks base method.
func (m *MockContainerManager) WaitForReady(ctx context.Context, containerID string, timeout time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForReady", ctx, containerID, timeout)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForReady indicates an expected call of WaitForReady.
func (mr *MockContainerManagerMockRecorder) WaitForReady(ctx, containerID, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForReady", reflect.TypeOf((*MockContainerManager)(nil).WaitForReady), ctx, containerID, timeout)
}
