// Code generated by MockGen. DO NOT EDIT.
// Source: gh.go
//
// Generated by this command:
//
//	mockgen -source=gh.go -destination=mock_gh.go -package=command
//

// Package command is a generated GoMock package.
package command

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGhRunner is a mock of GhRunner interface.
type MockGhRunner struct {
	ctrl     *gomock.Controller
	recorder *MockGhRunnerMockRecorder
	isgomock struct{}
}

// MockGhRunnerMockRecorder is the mock recorder for MockGhRunner.
type MockGhRunnerMockRecorder struct {
	mock *MockGhRunner
}

// NewMockGhRunner creates a new mock instance.
func NewMockGhRunner(ctrl *gomock.Controller) *MockGhRunner {
	mock := &MockGhRunner{ctrl: ctrl}
	mock.recorder = &MockGhRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGhRunner) EXPECT() *MockGhRunnerMockRecorder {
	return m.recorder
}

// GetLatestRunID mocks base method.
func (m *MockGhRunner) GetLatestRunID(ctx context.Context, dir string, prNumber int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestRunID", ctx, dir, prNumber)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestRunID indicates an expected call of GetLatestRunID.
func (mr *MockGhRunnerMockRecorder) GetLatestRunID(ctx, dir, prNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestRunID", reflect.TypeOf((*MockGhRunner)(nil).GetLatestRunID), ctx, dir, prNumber)
}

// GetPRBaseBranch mocks base method.
func (m *MockGhRunner) GetPRBaseBranch(ctx context.Context, dir, prNumber string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPRBaseBranch", ctx, dir, prNumber)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPRBaseBranch indicates an expected call of GetPRBaseBranch.
func (mr *MockGhRunnerMockRecorder) GetPRBaseBranch(ctx, dir, prNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPRBaseBranch", reflect.TypeOf((*MockGhRunner)(nil).GetPRBaseBranch), ctx, dir, prNumber)
}

// ListPRs mocks base method.
func (m *MockGhRunner) ListPRs(ctx context.Context, dir, branch string) ([]PRInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPRs", ctx, dir, branch)
	ret0, _ := ret[0].([]PRInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPRs indicates an expected call of ListPRs.
func (mr *MockGhRunnerMockRecorder) ListPRs(ctx, dir, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPRs", reflect.TypeOf((*MockGhRunner)(nil).ListPRs), ctx, dir, branch)
}

// PRChecks mocks base method.
func (m *MockGhRunner) PRChecks(ctx context.Context, dir string, prNumber int, jsonFields string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PRChecks", ctx, dir, prNumber, jsonFields)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PRChecks indicates an expected call of PRChecks.
func (mr *MockGhRunnerMockRecorder) PRChecks(ctx, dir, prNumber, jsonFields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PRChecks", reflect.TypeOf((*MockGhRunner)(nil).PRChecks), ctx, dir, prNumber, jsonFields)
}

// PRClose mocks base method.
func (m *MockGhRunner) PRClose(ctx context.Context, dir string, prNumber int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PRClose", ctx, dir, prNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// PRClose indicates an expected call of PRClose.
func (mr *MockGhRunnerMockRecorder) PRClose(ctx, dir, prNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PRClose", reflect.TypeOf((*MockGhRunner)(nil).PRClose), ctx, dir, prNumber)
}

// PRCreate mocks base method.
func (m *MockGhRunner) PRCreate(ctx context.Context, dir, title, body, head, base string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PRCreate", ctx, dir, title, body, head, base)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PRCreate indicates an expected call of PRCreate.
func (mr *MockGhRunnerMockRecorder) PRCreate(ctx, dir, title, body, head, base any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PRCreate", reflect.TypeOf((*MockGhRunner)(nil).PRCreate), ctx, dir, title, body, head, base)
}

// PREdit mocks base method.
func (m *MockGhRunner) PREdit(ctx context.Context, dir string, prNumber int, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PREdit", ctx, dir, prNumber, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// PREdit indicates an expected call of PREdit.
func (mr *MockGhRunnerMockRecorder) PREdit(ctx, dir, prNumber, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PREdit", reflect.TypeOf((*MockGhRunner)(nil).PREdit), ctx, dir, prNumber, body)
}

// PRView mocks base method.
func (m *MockGhRunner) PRView(ctx context.Context, dir string, prNumber int, jsonFields, jqQuery string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PRView", ctx, dir, prNumber, jsonFields, jqQuery)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PRView indicates an expected call of PRView.
func (mr *MockGhRunnerMockRecorder) PRView(ctx, dir, prNumber, jsonFields, jqQuery any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PRView", reflect.TypeOf((*MockGhRunner)(nil).PRView), ctx, dir, prNumber, jsonFields, jqQuery)
}

// RunRerun mocks base method.
func (m *MockGhRunner) RunRerun(ctx context.Context, dir string, runID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunRerun", ctx, dir, runID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunRerun indicates an expected call of RunRerun.
func (mr *MockGhRunnerMockRecorder) RunRerun(ctx, dir, runID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunRerun", reflect.TypeOf((*MockGhRunner)(nil).RunRerun), ctx, dir, runID)
}
